<?php

/** @var $user array */
/** @var $links array */
/** @var $stats array */

// Default view
$view = "all";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="<?php echo $this->getHost() ?>/assets/img/clypy.png" type="image/x-icon">
    <meta name="description"
          content="Clypy.me shorten your links and follow them to see their evulotion with statistical data">
    <meta name="author" content="Vince">
    <title>Dashboard - Clypy.me</title>
    c
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getHost() ?>/assets/css/uikit.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getHost() ?>/assets/css/dashboard.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">
</head>
<body>

<div class="loader">
    <div class="uk-position-center">
        <h1 style="color: #fff" class="uk-text-large uk-text-center uk-text-bolder">Clypy.me</h1>
    </div>
    <div class="lds-ellipsis">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<header id="top-head" class="uk-position-fixed">
    <div class="uk-container uk-container-expand uk-background-primary">
        <nav class="uk-navbar uk-light" data-uk-navbar="mode:click; duration: 250">
            <div class="uk-navbar-left">
                <div class="uk-navbar-item uk-hidden@m">
                    <a class="uk-logo" href="#"><img class="custom-logo"
                                                     src="<?php echo $this->getHost() ?>/assets/img/logo.png"
                                                     alt=""></a>
                </div>
            </div>
            <div class="uk-navbar-right">
                <ul class="uk-navbar-nav">
                    <li><a uk-toggle="target: #modal-toggle" data-uk-icon="icon:settings" title="Settings"
                           data-uk-tooltip></a></li>
                    <li><a href="../" data-uk-icon="icon: home" title="Home" data-uk-tooltip></a></li>
                    <li><a href="../logout.php" data-uk-icon="icon:  sign-out" title="Sign Out" data-uk-tooltip></a>
                    </li>
                    <li><a class="uk-navbar-toggle" data-uk-toggle data-uk-navbar-toggle-icon href="#offcanvas-nav"
                           title="Offcanvas" data-uk-tooltip></a></li>
                </ul>
            </div>
        </nav>
    </div>
</header>

<aside id="left-col" class="uk-light uk-visible@m">
    <div class="left-logo uk-flex uk-flex-middle">
        <img class="custom-logo" src="<?php echo $this->getHost() ?>/assets/img/logo.png" alt="logo">
    </div>
    <div class="left-content-box  content-box-dark">
        <img src="<?php echo $user['avatar'] ?>" alt="" class="uk-border-pill profile-img">
        <h4 class="uk-text-center uk-margin-remove-vertical text-light"><?php echo $user['username'] ?></h4>
    </div>
    <hr class="uk-divider-icon">
    <div class="left-nav-wrap">
        <ul class="uk-nav uk-nav-default uk-nav-parent-icon" data-uk-nav>
            <li class="uk-nav-header">ACTIONS</li>
            <li><a href="#modal-full" uk-toggle><span data-uk-icon="icon:  plus-circle"
                                                      class="uk-margin-small-right"></span>Create new link</a>
            <li class="uk-nav-header">LINKS</li>
            <?php
            if (count($links) > 0):
                foreach ($links as $link): ?>
                    <li id="<?php echo $link['link']['code'] ?>" class="uk-parent">
                        <a href="#"><span data-uk-icon="icon: link"
                                          class="uk-margin-small-right"></span><?php echo $link['link']['title'] ?></a>
                        <ul class="uk-subnav uk-flex uk-flex-center uk-child-width-1-4 uk-margin-small-top uk-margin-small-bottom"
                            data-uk-grid>
                            <li>
                                <a href="./<?php echo $link['link']['code'] ?>" class="uk-icon-link"
                                   data-uk-icon="icon: forward" title="View" data-uk-tooltip></a>
                            </li>
                            <li>
                                <a onclick="copy('<?php echo $link['link']['code'] ?>')" class="uk-icon-link"
                                   data-uk-icon="icon: copy" title="Copy" data-uk-tooltip></a>
                            </li>
                            <li>
                                <a onclick="edit('<?php echo $link['link']['code'] ?>','<?php echo $link['link']['title'] ?>')"
                                   class="uk-icon-link" data-uk-icon="icon: pencil" title="Edit" data-uk-tooltip></a>
                            </li>
                            <li>
                                <a onclick="trash('<?php echo $link['link']['code'] ?>','<?php echo $link['link']['title'] ?>')"
                                   class="uk-icon-link" data-uk-icon="icon: trash" title="Delete" data-uk-tooltip></a>
                            </li>
                        </ul>
                    </li>
                <?php
                endforeach;
            endif; ?>
        </ul>
    </div>
    <div class="bar-bottom">
        <ul class="uk-subnav uk-flex uk-flex-center uk-child-width-1-4" data-uk-grid>
            <li>
                <a href="../" class="uk-icon-link" data-uk-icon="icon: home" title="Home" data-uk-tooltip></a>
            </li>
            <li>
                <a class="uk-icon-link" data-uk-icon="icon: settings" title="Settings"
                   uk-toggle="target: #modal-toggle" data-uk-tooltip></a>
            </li>
            <li>
                <a href="../logout.php" class="uk-icon-link" data-uk-tooltip="Sign out"
                   data-uk-icon="icon: sign-out"></a>
            </li>
        </ul>
    </div>
</aside>

<div id="content" data-uk-height-viewport="expand: true">
    <div class="uk-container uk-container-expand">
        <!-- Header card -->
        <div class="uk-grid uk-grid-divider uk-grid-medium uk-child-width-1-2 uk-child-width-1-4@l uk-child-width-1-2@xl"
             data-uk-grid>
            <div>
        <span class="uk-text-small"><span data-uk-icon="icon:world"
                                          class="uk-margin-small-right uk-text-primary"></span>New Clicks</span>
                <h1 class="uk-heading-primary uk-margin-remove  uk-text-primary"><?php echo number_format($stats['thisWeek']) ?></h1>
                <div class="uk-text-small">
                    <?php if ($stats['percent'] > 0) { ?>
                        <span class="uk-text-success"
                              data-uk-icon="icon: triangle-up"><?php echo $stats['percent'] ?>%</span> more than last week.
                    <?php } else { ?>
                        <span class="uk-text-danger"
                              data-uk-icon="icon: triangle-down"><?php echo $stats['percent'] ?>%</span> less than last week.
                    <?php } ?>
                </div>
            </div>
            <div>

        <span class="uk-text-small"><span data-uk-icon="icon:link"
                                          class="uk-margin-small-right uk-text-primary"></span>Best link</span>
                <h1 class="uk-heading-primary uk-margin-remove uk-text-primary"><?php echo $stats['bestLink']['code'] ?></h1>
                <div class="uk-text-small">
                    <span class="uk-text-success"><?php echo $stats['bestLink']['count'] ?>%</span> Total clicks.
                </div>
            </div>
        </div>

        <hr class="uk-divider-icon">
        <div>
            <h1 class="uk-text-large uk-text-uppercase uk-text-center uk-text-bold"><span
                        uk-icon="chevron-down"></span> View of <?php echo $view ?> <span uk-icon="chevron-down"></span>
            </h1>
        </div>
        <hr class="uk-divider-icon">
        <div>
            <h1 class="uk-text-large uk-text-uppercase uk-text-bold">Links Charts</h1>
        </div>
        <div class="uk-grid uk-grid-medium" data-uk-grid>

            <div class="uk-width-2-3@l">
                <div class="uk-card uk-card-default uk-card-small uk-card-hover">
                    <div class="uk-card-header">
                        <div class="uk-grid uk-grid-small">
                            <div class="uk-width-auto">
                                <h4>Overview clicks <span id="chart-area-badge" class="uk-label">day</span></h4>
                            </div>
                            <div class="uk-width-expand uk-text-right panel-icons">
                                <a href="#offcanvas-slide-area" class="uk-icon-link" title="Configuration"
                                   data-uk-tooltip data-uk-icon="icon: cog" uk-toggle></a>
                                <a id="hide-show-area" class="uk-icon-link" title="Close" onclick="hideAreaChart()"
                                   data-uk-tooltip data-uk-icon="icon: close"></a>
                            </div>
                        </div>
                    </div>
                    <div id="card-area-chart" class="uk-card-body">
                        <div class="chart-container">
                            <div id="loader-area" style="height: 100%">
                                <div class="uk-position-center" role="status">
                                    <div uk-spinner></div>
                                </div>
                            </div>
                            <canvas id="myAreaChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            <div class="uk-width-1-3@l">
                <div class="uk-card uk-card-default uk-card-small uk-card-hover">
                    <div class="uk-card-header">
                        <div class="uk-grid uk-grid-small">
                            <div class="uk-width-auto">
                                <h4>Devices clicks <span id="chart-pie-badge" class="uk-label">day</span></h4>
                            </div>
                            <div class="uk-width-expand uk-text-right panel-icons">
                                <a href="#offcanvas-slide-pie" class="uk-icon-link" title="Configuration"
                                   data-uk-tooltip data-uk-icon="icon: cog" uk-toggle></a>
                                <a id="hide-show-pie" class="uk-icon-link" title="Close" onclick="hidePieChart()"
                                   data-uk-tooltip data-uk-icon="icon: close"></a>
                            </div>
                        </div>
                    </div>
                    <div id="card-pie-chart" class="uk-card-body">
                        <div class="chart-container">
                            <div id="loader-pie" style="height: 100%">
                                <div class="uk-position-center" role="status">
                                    <div uk-spinner></div>
                                </div>
                            </div>
                            <canvas id="myPieChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            <div class="uk-width-1-1 uk-width-1-3@l uk-width-1-3@xl">
                <div class="uk-card uk-card-default uk-card-small uk-card-hover">
                    <div class="uk-card-header">
                        <div class="uk-grid uk-grid-small">
                            <div class="uk-width-auto">
                                <h4>Location clicks <span class="uk-label">Total</span></h4>
                            </div>
                            <div class="uk-width-expand uk-text-right panel-icons">
                                <a id="hide-pie" class="uk-icon-link" title="Close" data-uk-tooltip
                                   onclick="hidePie()" data-uk-icon="icon: close"></a>
                            </div>
                        </div>
                    </div>
                    <div id="card-pie" class="uk-card-body">
                        <div class="chart-container">
                            <div id="loader-pie2" style="height: 100%">
                                <div class="uk-position-center" role="status">
                                    <div uk-spinner></div>
                                </div>
                            </div>
                            <canvas id="PieChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>

            <div class="uk-width-1-2@s uk-width-1-3@l uk-width-2-3@xl">
                <div class="uk-card uk-card-default uk-card-small uk-card-hover uk-panel">
                    <div class="uk-card-header">
                        <div class="uk-grid uk-grid-small">
                            <div class="uk-width-auto">
                                <h4>Browser clicks <span class="uk-label">Total</span></h4>
                            </div>
                            <div class="uk-width-expand uk-text-right panel-icons">
                                <a id="hide-bar" class="uk-icon-link" title="Close" data-uk-tooltip
                                   onclick="hideBar()" data-uk-icon="icon: close"></a>
                            </div>
                        </div>
                    </div>
                    <div id="card-bar" class="uk-card-body">
                        <div class="chart-container">
                            <div id="loader-bar" style="height: 100%">
                                <div class="uk-position-center" role="status">
                                    <div uk-spinner></div>
                                </div>
                            </div>
                            <canvas id="myBarChart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="uk-divider-icon">
        <div>
            <h1 class="uk-text-large uk-text-uppercase uk-text-bold">Links Table</h1>
        </div>
        <div class="uk-overflow-auto">
            <table class="uk-table uk-table-divider">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>URL</th>
                    <th>Protocol</th>
                    <th>Link</th>
                    <th>Owner</th>
                    <th>Date</th>
                    <th>Clicks</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($links as $link): ?>
                    <tr id="<?php echo $link['link']['code'] ?>">
                        <td id="edit<?php echo $link['link']['code'] ?>"><?php echo $link['link']['title'] ?></td>
                        <td><?php echo $link['link']['links_origin'] ?></td>
                        <td><?php echo $link['link']['isHTTPS'] == 1 ? "HTTPS" : "HTTP" ?></td>
                        <td><a href="<?php echo $this->getHost() . "/" . $link['link']['code'] ?>"
                               target="_blank"><?php echo $this->getHost() . "/" . $link['link']['code'] ?></a></td>
                        <td><?php echo $link['link']['owner_username'] ?></td>
                        <td><?php echo date("Y/m/d", $link['link']['date_link']); ?></td>
                        <td><?php echo $link['clickCount'] ?></td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <footer class="uk-section uk-section-small uk-text-center">
            <hr class="uk-divider-icon">
            <p class="uk-text-small uk-text-center">Copyright &copy; Clypy 2020</p>
        </footer>
    </div>
</div>

<div id="offcanvas-nav" data-uk-offcanvas="flip: true; overlay: true">
    <div class="uk-offcanvas-bar uk-offcanvas-bar-animation uk-offcanvas-slide">
        <button class="uk-offcanvas-close uk-close uk-icon" type="button" data-uk-close></button>
        <div class="left-content-box  content-box-dark">
            <img src="<?php echo $user['avatar'] ?>" alt="" class="uk-border-pill profile-img">
            <h4 class="uk-text-center uk-margin-remove-vertical text-light"><?php echo $user['username'] ?></h4>
        </div>
        <hr class="uk-divider-icon">
        <ul class="uk-nav uk-nav-default uk-nav-parent-icon " data-uk-nav>
            <li class="uk-nav-header">ACTIONS</li>
            <li><a href="#modal-full" uk-toggle><span data-uk-icon="icon:  plus-circle"
                                                      class="uk-margin-small-right"></span>Create new link</a>
            <li class="uk-nav-header">LINKS</li>
            <?php foreach ($links as $link): ?>
                <li class="uk-parent">
                    <a><span data-uk-icon="icon: link"
                             class="uk-margin-small-right"></span><?php echo $link['link']['title'] ?></a>
                    <ul class="uk-flex uk-flex-center uk-child-width-1-4 uk-margin-small-top uk-margin-small-bottom uk-nav-sub">
                        <li>
                            <a href="./<?php echo $link['link']['code'] ?>" class="uk-icon-link"
                               data-uk-icon="icon: forward" title="View" data-uk-tooltip></a>
                        </li>
                        <li>
                            <a onclick="copy('<?php echo $link['link']['code'] ?>')" class="uk-icon-link"
                               data-uk-icon="icon: copy" title="Copy" data-uk-tooltip></a>
                        </li>
                        <li>
                            <a onclick="edit('<?php echo $link['link']['code'] ?>','<?php echo $link["link"]["title"] ?>')"
                               class="uk-icon-link" data-uk-icon="icon: pencil" title="Edit" data-uk-tooltip></a>
                        </li>
                        <li>
                            <a onclick="trash('<?php echo $link['link']['code'] ?>','<?php echo $link["link"]["code"] ?>')"
                               class="uk-icon-link" data-uk-icon="icon: trash" title="Delete" data-uk-tooltip></a>
                        </li>
                    </ul>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>

<div id="offcanvas-slide-area" uk-offcanvas>
    <div class="uk-offcanvas-bar">
        <ul class="uk-nav uk-nav-default uk-position-center">
            <li class="uk-nav-header">Overview clicks sort by:</li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="clicksChartArea('<?php echo $view ?>','day')">Day</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="clicksChartArea('<?php echo $view ?>','week')">Week</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="clicksChartArea('<?php echo $view ?>','month')">Month</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="clicksChartArea('<?php echo $view ?>','year')">Year</a></li>
        </ul>
    </div>
</div>

<div id="offcanvas-slide-pie" uk-offcanvas>
    <div class="uk-offcanvas-bar">
        <ul class="uk-nav uk-nav-default uk-position-center">
            <li class="uk-nav-header">Devices clicks sort by:</li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="chartPie('<?php echo $view ?>','day')">Day</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="chartPie('<?php echo $view ?>','week')">Week</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="chartPie('<?php echo $view ?>','month')">Month</a></li>
            <li><a class="uk-button uk-button-default uk-button-small uk-margin-small-top"
                   onclick="chartPie('<?php echo $view ?>','year')">Year</a></li>
        </ul>
    </div>
</div>

<div id="modal-full" class="uk-modal-full uk-modal" uk-modal>
    <div class="uk-modal-dialog uk-flex uk-flex-center uk-flex-middle" uk-height-viewport>
        <button class="uk-modal-close-full" type="button" uk-close></button>
        <form class="uk-search uk-search-large" action="" method="POST">
            <p class="uk-text-center">Create your link shorted</p>
            <input class="uk-search-input uk-text-center" name="title" type="text" placeholder="Title" required>
            <hr class="uk-divider-icon">
            <input class="uk-search-input uk-text-center" name="url_origin" type="url" placeholder="Paste long url"
                   required>
            <br/>
            <br/>
            <br/>
            <button class="uk-button uk-button-default uk-button-small uk-align-center" type="submit">Create
                link
            </button>
        </form>
    </div>
</div>

<div id="modal-toggle" uk-modal>
    <div class="uk-modal-dialog">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <div class="uk-modal-header">
            <h3 class="uk-modal-title">Settings</h3>
        </div>
        <div class="uk-margin-medium-top">
            <ul class="uk-flex-center" uk-tab>
                <li class="uk-active"><a onclick="openPage('profile')">Profile</a></li>
                <li><a onclick="openPage('password')">Password</a></li>
                <li><a onclick="openPage('delete')">Delete</a></li>
            </ul>
        </div>
        <div class="uk-modal-body" uk-overflow-auto>
            <div class="page" id="profile">
                <div class="left-content-box  content-box-dark">
                    <img src="<?php echo $user['avatar'] ?>" alt="" class="uk-border-pill profile-img">
                    <h4 class="uk-text-center uk-margin-remove-vertical text-light"><?php echo $user['username']; ?></h4>
                </div>
                <div class="uk-margin">
                    <label class="uk-form-label" for="form-stacked-text">Username</label>
                    <div class="uk-form-controls">
                        <input placeholder="Username" class="uk-input" id="username" type="text"
                               value="<?php echo $user['username']; ?>"
                               required>
                    </div>
                </div>
                <button id="submitProfile" class="uk-button uk-button-primary uk-align-right">Save
                    Profile
                </button>
            </div>
            <div style="display: none" class="page" id="password">
                <div class="uk-margin">
                    <label class="uk-form-label" for="form-stacked-text">Old Password</label>
                    <div class="uk-form-controls">
                        <input class="uk-input" id="oldPassword" type="password" placeholder="Password" required>
                    </div>
                </div>
                <div class="uk-margin">
                    <label class="uk-form-label" for="form-stacked-text">New Password</label>
                    <div class="uk-form-controls">
                        <input class="uk-input" id="newPassword" type="password" placeholder="New Password" required>
                    </div>
                </div>
                <div class="uk-margin">
                    <label class="uk-form-label" for="form-stacked-text">Retype New Password</label>
                    <div class="uk-form-controls">
                        <input class="uk-input" id="newPasswordVerif" type="password" placeholder="Retype New Password"
                               required>
                    </div>
                </div>
                <button id="submitPassword" class="uk-button uk-button-primary uk-align-right">Save Password</button>
            </div>
            <div style="display: none" class="page" id="delete">
                <p>If you delete your account there will be no way to recover it, all your data will be deleted as well
                    as all your links</p>
                <button id="deleteAccount" class="uk-button uk-button-danger uk-align-center">Delete your account
                </button>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->getHost() ?>/assets/js/uikit.min.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/uikit-icons.min.js"></script>
<script src="<?php echo $this->getHost() ?>/vendor/jquery/jquery.min.js"></script>
<script src="<?php echo $this->getHost() ?>/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?php echo $this->getHost() ?>/vendor/chart.js/Chart.min.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/sweetalert2@8.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/clicksChartArea.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/deviceClickChartDog.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/locationClickChartPie.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/browerClickChartBar.js"></script>
<script src="<?php echo $this->getHost() ?>/assets/js/functions.js"></script>
<script>
    // Hide loader
    window.addEventListener("load", function () {
        const loader = document.querySelector(".loader");
        loader.className += " hidden";
    });

    /**
     * Number format
     *
     * @param number
     * @param decimals
     * @param dec_point
     * @param thousands_sep
     * @return {string}
     */
    function number_format(number, decimals, dec_point, thousands_sep) {
        number = (number + '').replace(',', '').replace(' ', '');
        let n = !isFinite(+number) ? 0 : +number,
            prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
            sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
            dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
            s = '',
            toFixedFix = function (n, prec) {
                let k = Math.pow(10, prec);
                return '' + Math.round(n * k) / k;
            };
        s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
        if (s[0].length > 3) {
            s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
        }
        if ((s[1] || '').length < prec) {
            s[1] = s[1] || '';
            s[1] += new Array(prec - s[1].length + 1).join('0');
        }
        return s.join(dec);
    }

    /**
     * Time converter
     * @param UNIX_timestamp
     * @return {string}
     */
    function timeConverter(UNIX_timestamp) {
        let a = new Date(UNIX_timestamp * 1000);
        let months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
        let year = a.getFullYear();
        let month = months[a.getMonth()];
        let date = a.getDate();
        let hour = a.getHours();
        let min = a.getMinutes();
        let sec = a.getSeconds();
        return date + ' ' + month + ' ' + year;
    }

    // Default req
    clicksChartArea('<?php echo $view ?>', 'day');
    browerClickChartBar('<?php echo $view ?>', 'day');
    chartsPie("<?php echo $view ?>");
    chartPie('<?php echo $view ?>', 'day');
</script>